import type { Metadata } from "next";
import { Geist, Geist_Mono, Michroma,Rajdhani, Scheherazade_New} from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ScrollToTop from "@/components/ui/ScrollToTop";
import WhatsAppChat from "@/components/ui/WhatsAppChat";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const michroma = Michroma({
  weight: "400", // Michroma suele tener solo peso 400
  subsets: ["latin"],
  variable: "--font-michroma", // Define una variable CSS
});
const rajdhani = Rajdhani({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-rajdhani",
});
const Scheherazade = Scheherazade_New({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-Scheherazade",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${michroma.variable} ${rajdhani.variable} ${Scheherazade.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <Navbar />
        <main className="flex-grow">
          {children}
        </main>
        <WhatsAppChat />
        <ScrollToTop />
        <Footer />
      </body>
    </html>
  );
}
